"""added top_speed coloumn

Revision ID: 16da843b276e
Revises: 259d07c23efc
Create Date: 2026-07-08 12:40:39.136537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16da843b276e'
down_revision: Union[str, Sequence[str], None] = '259d07c23efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('top_speed', sa.Integer(), nullable=True))
    op.alter_column('motorcycles', 'make',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('motorcycles', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('motorcycles', 'year',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.create_index(op.f('ix_motorcycles_category'), 'motorcycles', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_motorcycles_category'), table_name='motorcycles')
    op.alter_column('motorcycles', 'year',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.alter_column('motorcycles', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('motorcycles', 'make',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('motorcycles', 'top_speed')
    # ### end Alembic commands ###
