"""simplify motorcycles schema for api ninjas source

Revision ID: 259d07c23efc
Revises: 4e646dff9c74
Create Date: 2026-07-07 20:52:45.307924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '259d07c23efc'
down_revision: Union[str, Sequence[str], None] = '4e646dff9c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("TRUNCATE TABLE motorcycles")

    op.add_column('motorcycles', sa.Column('raw_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_unique_constraint('uq_motorcycle_make_model_year', 'motorcycles', ['make', 'model', 'year'])
    op.drop_column('motorcycles', 'front_brake')
    op.drop_column('motorcycles', 'horsepower')
    op.drop_column('motorcycles', 'front_tire')
    op.drop_column('motorcycles', 'seat_height')
    op.drop_column('motorcycles', 'total_width')
    op.drop_column('motorcycles', 'clutch')
    op.drop_column('motorcycles', 'total_height')
    op.drop_column('motorcycles', 'raw_data')
    op.drop_column('motorcycles', 'torque_nm')
    op.drop_column('motorcycles', 'displacement')
    op.drop_column('motorcycles', 'suspension')
    op.drop_column('motorcycles', 'total_weight')
    op.drop_column('motorcycles', 'rear_brake')
    op.drop_column('motorcycles', 'total_length')
    op.drop_column('motorcycles', 'rear_tire')
    op.drop_column('motorcycles', 'engine_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('engine_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('rear_tire', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('total_length', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('rear_brake', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('total_weight', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('suspension', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('displacement', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('torque_nm', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('total_height', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('clutch', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('total_width', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('seat_height', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('front_tire', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('horsepower', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('motorcycles', sa.Column('front_brake', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint('uq_motorcycle_make_model_year', 'motorcycles', type_='unique')
    op.drop_column('motorcycles', 'raw_specs')
    # ### end Alembic commands ###
