"""create motorcycles table

Revision ID: 4e646dff9c74
Revises: 
Create Date: 2026-07-07 19:03:58.887064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e646dff9c74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motorcycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('engine_type', sa.String(length=100), nullable=True),
    sa.Column('displacement', sa.String(length=100), nullable=True),
    sa.Column('horsepower', sa.String(length=100), nullable=True),
    sa.Column('torque_nm', sa.String(length=100), nullable=True),
    sa.Column('total_weight', sa.String(length=100), nullable=True),
    sa.Column('total_height', sa.String(length=100), nullable=True),
    sa.Column('total_width', sa.String(length=100), nullable=True),
    sa.Column('total_length', sa.String(length=100), nullable=True),
    sa.Column('seat_height', sa.String(length=100), nullable=True),
    sa.Column('front_tire', sa.String(length=100), nullable=True),
    sa.Column('rear_tire', sa.String(length=100), nullable=True),
    sa.Column('front_brake', sa.String(length=100), nullable=True),
    sa.Column('rear_brake', sa.String(length=100), nullable=True),
    sa.Column('suspension', sa.String(length=100), nullable=True),
    sa.Column('clutch', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motorcycles_make'), 'motorcycles', ['make'], unique=False)
    op.create_index(op.f('ix_motorcycles_model'), 'motorcycles', ['model'], unique=False)
    op.create_index(op.f('ix_motorcycles_year'), 'motorcycles', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_motorcycles_year'), table_name='motorcycles')
    op.drop_index(op.f('ix_motorcycles_model'), table_name='motorcycles')
    op.drop_index(op.f('ix_motorcycles_make'), table_name='motorcycles')
    op.drop_table('motorcycles')
    # ### end Alembic commands ###
