"""added parsed data columns used for charts

Revision ID: 6a17052ea3f0
Revises: f4b9b890e479
Create Date: 2026-07-11 19:32:35.131567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a17052ea3f0'
down_revision: Union[str, Sequence[str], None] = 'f4b9b890e479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('horsepower', sa.NUMERIC(), nullable=True))
    op.add_column('motorcycles', sa.Column('torque_nm', sa.NUMERIC(), nullable=True))
    op.add_column('motorcycles', sa.Column('weight_kg', sa.NUMERIC(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motorcycles', 'weight_kg')
    op.drop_column('motorcycles', 'torque_nm')
    op.drop_column('motorcycles', 'horsepower')
    # ### end Alembic commands ###
