"""add crashes and crash_vehicle tables

Revision ID: 82a0515566ea
Revises: 9b1a6d33d036
Create Date: 2026-07-19 13:52:46.019007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a0515566ea'
down_revision: Union[str, Sequence[str], None] = '9b1a6d33d036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crashes',
    sa.Column('collision_id', sa.Integer(), nullable=False),
    sa.Column('crash_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=False),
    sa.Column('longitude', sa.Numeric(), nullable=False),
    sa.Column('borough', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('on_street_name', sa.String(), nullable=True),
    sa.Column('cross_street_name', sa.String(), nullable=True),
    sa.Column('off_street_name', sa.String(), nullable=True),
    sa.Column('motorcycle_involved', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.Enum('FATAL', 'INJURY', 'PROPERTY_DAMAGE', name='severityenum'), nullable=False),
    sa.Column('persons_injured', sa.Integer(), nullable=True),
    sa.Column('persons_killed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('collision_id')
    )
    op.create_index(op.f('ix_crashes_borough'), 'crashes', ['borough'], unique=False)
    op.create_index(op.f('ix_crashes_crash_datetime'), 'crashes', ['crash_datetime'], unique=False)
    op.create_index(op.f('ix_crashes_motorcycle_involved'), 'crashes', ['motorcycle_involved'], unique=False)
    op.create_index(op.f('ix_crashes_severity'), 'crashes', ['severity'], unique=False)
    op.create_table('crash_vechicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collision_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_number', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('contributing_factor', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collision_id'], ['crashes.collision_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crash_vechicle_collision_id'), 'crash_vechicle', ['collision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crash_vechicle_collision_id'), table_name='crash_vechicle')
    op.drop_table('crash_vechicle')
    op.drop_index(op.f('ix_crashes_severity'), table_name='crashes')
    op.drop_index(op.f('ix_crashes_motorcycle_involved'), table_name='crashes')
    op.drop_index(op.f('ix_crashes_crash_datetime'), table_name='crashes')
    op.drop_index(op.f('ix_crashes_borough'), table_name='crashes')
    op.drop_table('crashes')
    # ### end Alembic commands ###
