"""added displacement column

Revision ID: 9b1a6d33d036
Revises: 6a17052ea3f0
Create Date: 2026-07-16 15:29:40.919496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1a6d33d036'
down_revision: Union[str, Sequence[str], None] = '6a17052ea3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('displacement', sa.NUMERIC(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motorcycles', 'displacement')
    # ### end Alembic commands ###
