"""drop unused categories coloumn

Revision ID: f4b9b890e479
Revises: 16da843b276e
Create Date: 2026-07-09 14:00:52.336245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b9b890e479'
down_revision: Union[str, Sequence[str], None] = '16da843b276e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_motorcycles_category'), table_name='motorcycles')
    op.drop_column('motorcycles', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_motorcycles_category'), 'motorcycles', ['category'], unique=False)
    # ### end Alembic commands ###
